"""E13 AutoGen generator — `DeclaredContract` → runnable AutoGen GroupChat module source.

Same YAML, second framework: this is the framework-agnostic claim made concrete (E13 §B). Mapping:
  agents[]          -> ConversableAgent (instructions -> system_message, model -> llm_config)
  delegations       -> GroupChat.allowed_or_disallowed_speaker_transitions ("allowed")
  coordinator       -> the initial speaker (returned alongside the manager)
  rules (deny)      -> the forbidden transition is simply never emitted (creation-driven)

Shares coordinator detection + the acyclic/scope-monotonic guard with the LangGraph target, so a
graph that won't generate for one target won't generate for the other. Pure string generation (no
autogen import here). Tool binding is LangGraph-complete; AutoGen tool registration is a follow-on
(noted in the generated header), so this target carries instructions/model/delegations today.
"""
from __future__ import annotations

from ..library.contract import DeclaredContract
from .langgraph import coordinator
from .validate import validate_for_generation

_HEADER = (
    '"""Generated by AgentGate — E13 codegen (AutoGen target) — do not edit.\n'
    'Regenerate from the AgenticArchitecture; edits are overwritten.\n'
    "Note: delegations/instructions/model are wired; per-agent tool registration is a follow-on.\"\"\""
)


def generate_autogen(contract: DeclaredContract, *, entry: str | None = None) -> str:
    """Generate an AutoGen GroupChat module (as source text) from a declared contract."""
    if not contract.agents:
        raise ValueError("contract has no agents — nothing to generate")
    validate_for_generation(contract)   # acyclic + scope-monotonic, same guard as LangGraph
    entry = entry or coordinator(contract)
    if entry not in contract.agents:
        raise ValueError(f"entry {entry!r} is not a declared agent")

    names = sorted(contract.agents)
    out: list[str] = [
        _HEADER,
        "from autogen import ConversableAgent, GroupChat, GroupChatManager",
        "",
        "",
        "def build_group_chat(llm_config=None):",
    ]
    for name in names:
        a = contract.agents[name]
        cfg = f"{{'model': {a.model!r}}}" if a.model else "llm_config"
        out += [
            f"    {name} = ConversableAgent(",
            f"        {name!r}, system_message={a.instructions!r},",
            f"        llm_config={cfg})",
        ]
    out.append("")
    out.append("    _agents = [" + ", ".join(names) + "]")
    # declared transitions only — an undeclared hand-off is never generated (creation-driven)
    out.append("    allowed = {")
    for name in names:
        targets = sorted(contract.agents[name].can_delegate_to)
        out.append(f"        {name}: [" + ", ".join(targets) + "],")
    out.append("    }")
    out += [
        "    chat = GroupChat(",
        "        agents=_agents, messages=[],",
        "        allowed_or_disallowed_speaker_transitions=allowed,",
        "        speaker_transitions_type='allowed')",
        "    manager = GroupChatManager(groupchat=chat, llm_config=llm_config)",
        f"    return manager, {entry}   # (manager, coordinator / initial speaker)",
        "",
    ]
    return "\n".join(out)
