"""E13 CrewAI generator — `DeclaredContract` → runnable CrewAI module source.

Third framework, same YAML (E13 §B). CrewAI models work as Agents + Tasks run by a Crew, so the
delegation DAG maps to a **sequential pipeline** in topological order (delegators before
delegatees); each agent's `instructions` become its backstory and one Task. Mapping:
  agents[]          -> Agent (instructions -> backstory, role/name -> role, model -> llm)
  delegations (DAG) -> Task order (topological) + allow_delegation where the agent has out-edges
  coordinator       -> first task's agent
  rules/undeclared  -> not represented (no edge to emit); creation-driven holds via the fixed order

Shares the acyclic/scope-monotonic guard with the other targets. Pure string generation (no crewai
import here). CrewAI's hierarchical/manager delegation is a follow-on; this MVP emits the sequential
process, which is deterministic and matches the declared order.
"""
from __future__ import annotations

from ..library.contract import DeclaredContract
from .langgraph import coordinator
from .validate import topological_order, validate_for_generation

_HEADER = (
    '"""Generated by AgentGate — E13 codegen (CrewAI target) — do not edit.\n'
    'Regenerate from the AgenticArchitecture; edits are overwritten.\n'
    'Note: sequential process in declared (topological) order; hierarchical delegation is a follow-on.\"\"\"'
)


def generate_crewai(contract: DeclaredContract, *, entry: str | None = None) -> str:
    """Generate a CrewAI module (as source text) from a declared contract."""
    if not contract.agents:
        raise ValueError("contract has no agents — nothing to generate")
    validate_for_generation(contract)   # acyclic + scope-monotonic, same guard as the other targets
    entry = entry or coordinator(contract)
    if entry not in contract.agents:
        raise ValueError(f"entry {entry!r} is not a declared agent")

    order = topological_order(contract)   # delegators before delegatees (coordinator first)
    out: list[str] = [
        _HEADER,
        "from crewai import Agent, Crew, Process, Task",
        "",
        "",
        "def build_crew(llm=None):",
    ]
    for name in order:
        a = contract.agents[name]
        goal = a.role or f"Carry out the {name} role"
        out += [
            f"    {name} = Agent(",
            f"        role={name!r}, goal={goal!r}, backstory={a.instructions!r},",
            f"        llm={a.model!r} if {bool(a.model)!r} else llm, "
            f"allow_delegation={bool(a.can_delegate_to)!r})",
        ]
    out.append("")
    for name in order:
        a = contract.agents[name]
        out += [
            f"    t_{name} = Task(",
            f"        description={a.instructions!r},",
            f"        agent={name}, expected_output='the agent\\'s contribution toward the goal')",
        ]
    out.append("")
    out += [
        "    return Crew(",
        "        agents=[" + ", ".join(order) + "],",
        "        tasks=[" + ", ".join(f"t_{n}" for n in order) + "],",
        "        process=Process.sequential)",
        "",
    ]
    return "\n".join(out)
