"""E13 LangGraph generator — `DeclaredContract` → runnable LangGraph module source (E13 §B).

Mapping (design §B):
  agents[]          -> graph nodes (instructions -> prompt, model -> LLM, tools -> bound tools)
  delegations       -> graph edges (ONLY declared canDelegateTo edges are emitted)
  coordinator       -> entry point (the agent no one delegates to — the pyramid apex)
  leaf agents       -> edge to END
  rules (deny)      -> the forbidden edge is simply never emitted (creation-driven)

The output is a self-describing Python module string; `build_graph()` returns a compiled LangGraph.
Node bodies call `agentgate.codegen.runtime.make_agent_node` (the execute layer, phase 4), so the
generated module stays small and the runtime is swappable. Pure string generation — no LangChain
import here, so codegen runs anywhere (the generated app is what needs the framework installed).
"""
from __future__ import annotations

from ..library.contract import DeclaredContract
from .validate import validate_for_generation

_HEADER ='"""Generated by DriftWatch E13 codegen (LangGraph target) — do not edit.\nRegenerate from the AgenticArchitecture; edits are overwritten."""'


def coordinator(contract: DeclaredContract) -> str:
    """The graph's entry agent: the one no other agent delegates to (the pyramid apex).

    If several agents have no incoming edge, prefer a `strategic`-tier one, then lexical order, for
    deterministic output. Raises if there is no entry (every agent is a target → cyclic / no apex).
    """
    if not contract.agents:
        raise ValueError("contract has no agents — nothing to generate")
    targets = {dst for a in contract.agents.values() for dst in a.can_delegate_to}
    roots = [n for n in contract.agents if n not in targets]
    if not roots:
        raise ValueError(
            "no coordinator: every agent is a delegation target (no entry / graph is cyclic)"
        )
    roots.sort(key=lambda n: (contract.agents[n].tier != "strategic", n))
    return roots[0]


def generate_langgraph(
    contract: DeclaredContract, *, entry: str | None = None, dynamic: bool = False,
) -> str:
    """Generate a LangGraph module (as source text) from a declared contract.

    `entry` overrides the auto-detected coordinator. **Static** (default): only declared edges are
    emitted, so an undeclared hand-off cannot exist (creation-driven, E13 6a). **Dynamic**
    (`dynamic=True`, E13 6b): each non-leaf agent picks its next hand-off at run time, gated by the
    embedded contract against the declared graph (observability-driven) — a novel/cyclic/escalating
    pick is recorded and (action=block) routed to END.
    """
    if not contract.agents:
        raise ValueError("contract has no agents — nothing to generate")
    validate_for_generation(contract)   # acyclic + scope-monotonic, or it does not generate
    entry = entry or coordinator(contract)
    if entry not in contract.agents:
        raise ValueError(f"entry {entry!r} is not a declared agent")
    if dynamic:
        return _generate_dynamic(contract, entry)

    out: list[str] = [
        _HEADER,
        "from langgraph.graph import END, StateGraph",
        "from agentgate.codegen.runtime import make_agent_node",
        "",
        "",
        "def build_graph():",
        "    g = StateGraph(dict)",
    ]
    for name in sorted(contract.agents):
        a = contract.agents[name]
        prov, model, ep = contract.effective_llm(name)
        out += [
            f"    g.add_node({name!r}, make_agent_node(",
            f"        name={name!r}, model={model!r}, "
            f"llm_provider={prov!r}, llm_endpoint={ep!r},",
            f"        instructions={a.instructions!r},",
            f"        tools={sorted(a.allowed_tools)!r}, "
            f"mcp_backends={sorted(a.mcp_backends)!r},",
            f"        emit_attributes={list(contract.emit_attributes)!r}))",
        ]
    out.append("")
    # declared delegation edges only — an undeclared edge is never generated (creation-driven)
    for name in sorted(contract.agents):
        for dst in sorted(contract.agents[name].can_delegate_to):
            out.append(f"    g.add_edge({name!r}, {dst!r})")
    # leaf agents (no outgoing delegation) terminate the graph
    for name in sorted(contract.agents):
        if not contract.agents[name].can_delegate_to:
            out.append(f"    g.add_edge({name!r}, END)")
    out += [
        f"    g.set_entry_point({entry!r})",
        "    return g.compile()",
        "",
    ]
    return "\n".join(out)


def _generate_dynamic(contract: DeclaredContract, entry: str) -> str:
    """Dynamic LangGraph (E13 6b): agents pick + the runtime gates each hand-off vs the declared graph."""
    out: list[str] = [
        _HEADER,
        "import os",
        "",
        "from langgraph.graph import END, StateGraph",
        "",
        "from agentgate.codegen.runtime import make_agent_node, make_router",
        "from agentgate.library.contract import DeclaredContract",
        "",
        f"_CONTRACT = DeclaredContract.from_dict({contract.to_dict()!r})",
        '_ACTION = (os.environ.get("AGENTGATE_DELEGATION_ACTION")'
        ' or os.environ.get("DRIFTWATCH_DELEGATION_ACTION") or "block")',
        "",
        "",
        "def build_graph():",
        "    g = StateGraph(dict)",
    ]
    for name in sorted(contract.agents):
        a = contract.agents[name]
        prov, model, ep = contract.effective_llm(name)
        out += [
            f"    g.add_node({name!r}, make_agent_node(",
            f"        name={name!r}, model={model!r}, instructions={a.instructions!r},",
            f"        llm_provider={prov!r}, llm_endpoint={ep!r},",
            f"        tools={sorted(a.allowed_tools)!r}, "
            f"can_delegate_to={sorted(a.can_delegate_to)!r},",
            "        contract=_CONTRACT, delegation_action=_ACTION,",
            f"        mcp_backends={sorted(a.mcp_backends)!r}, "
            f"emit_attributes={list(contract.emit_attributes)!r}))",
        ]
    out.append("")
    # non-leaf agents route at run time (gated in the node); leaves terminate
    for name in sorted(contract.agents):
        targets = sorted(contract.agents[name].can_delegate_to)
        if targets:
            mapping = ", ".join(f"{t!r}: {t!r}" for t in targets) + ", '__end__': END"
            out.append(f"    g.add_conditional_edges({name!r}, "
                       f"make_router(action=_ACTION, allowed={targets!r}), "
                       f"{{{mapping}}})")
        else:
            out.append(f"    g.add_edge({name!r}, END)")
    out += [
        f"    g.set_entry_point({entry!r})",
        "    return g.compile()",
        "",
    ]
    return "\n".join(out)
